/**
 * Generated by Postman Code
 * Collection: Edge Impulse API
 * Request: Projects > List Projects
 */
import type { ListProjectsResponse, EdgeImpulseError } from "../../shared/types";

/**
 * List all Edge Impulse projects for the authenticated user.
 * @param apiKey - Edge Impulse API key
 * @returns List of projects
 */
export async function listProjects(apiKey: string): Promise<ListProjectsResponse> {
  const url = "https://studio.edgeimpulse.com/v1/api/projects";
  const response = await fetch(url, {
    headers: {
      "x-api-key": apiKey,
      "Content-Type": "application/json"
    }
  });
  if (response.ok) {
    return (await response.json()) as ListProjectsResponse;
  }
  const error = (await response.json()) as EdgeImpulseError;
  throw new Error(`Edge Impulse API error: ${error.message}`);
}
