/**
 * Generated by Postman Code
 * Collection: Edge Impulse API
 * Request: Projects > Upload Data
 */
import type { UploadDataRequest, UploadDataResponse, EdgeImpulseError } from "../../shared/types";

/**
 * Upload data to an Edge Impulse project.
 * @param apiKey - Edge Impulse API key
 * @param req - Upload data request
 * @returns Upload result
 */
export async function uploadData(apiKey: string, req: UploadDataRequest): Promise<UploadDataResponse> {
  const url = `https://studio.edgeimpulse.com/v1/api/${req.projectId}/data`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      // Content-Type may need to be set based on data type
    },
    body: req.data
  });
  if (response.ok) {
    return (await response.json()) as UploadDataResponse;
  }
  const error = (await response.json()) as EdgeImpulseError;
  throw new Error(`Edge Impulse API error: ${error.message}`);
}
