/**
 * Generated by Postman Code
 * Collection: Edge Impulse API
 * Request: Projects > Upload Data
 */
import type { UploadDataRequest, UploadDataResponse, EdgeImpulseError } from "../../shared/types";

/**
 * Upload data to an Edge Impulse project.
 * @param apiKey - Edge Impulse API key
 * @param req - Upload data request
 * @returns Upload result
 */
export async function uploadData(apiKey: string, req: UploadDataRequest): Promise<UploadDataResponse> {
  const url = `https://studio.edgeimpulse.com/v1/api/${req.projectId}/data`;
  let body: BodyInit;
  const headers: Record<string, string> = {
    "x-api-key": apiKey,
  };
  const suppliedContentType = (req as any).contentType as string | undefined;
  if (typeof req.data === 'string') {
    body = req.data;
    // If the caller didn't provide a contentType, assume text/plain
    headers['Content-Type'] = suppliedContentType || 'text/plain';
  } else if (req.data instanceof Buffer) {
    // Node Buffer is acceptable for BodyInit at runtime; set a sensible default
    body = req.data as unknown as BodyInit;
    headers['Content-Type'] = suppliedContentType || 'application/octet-stream';
  } else {
    throw new Error('Invalid data type for upload: must be string or Buffer');
  }

  const response = await fetch(url, {
    method: "POST",
    headers,
    body
  });

  if (response.ok) {
    return (await response.json()) as UploadDataResponse;
  }

  // Provide rich error output for easier debugging (like other clients)
  const errorText = await response.text();
  try {
    const error = JSON.parse(errorText) as EdgeImpulseError;
    throw new Error(`Edge Impulse API error: ${error.message}`);
  } catch {
    throw new Error(`Edge Impulse API error: ${response.status} ${response.statusText} - ${errorText}`);
  }
}
