/**
 * Generated by Postman Code
 * Collection: Edge Impulse API
 * Request: Training > Start Training
 */
import type { StartTrainingRequest, StartTrainingResponse, EdgeImpulseError } from "../../shared/types";

/**
 * Start model training for an Edge Impulse project.
 * @param apiKey - Edge Impulse API key
 * @param req - Start training request
 * @returns Training job info
 */
export async function startTraining(apiKey: string, req: StartTrainingRequest): Promise<StartTrainingResponse> {
  const url = `https://studio.edgeimpulse.com/v1/api/${req.projectId}/jobs/train`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({})
  });
  if (response.ok) {
    return (await response.json()) as StartTrainingResponse;
  }
  const error = (await response.json()) as EdgeImpulseError;
  throw new Error(`Edge Impulse API error: ${error.message}`);
}
